### ISSUE TITLE
Add a start at boot option.

### ISSUE THREAD

**Issue by styromaniac** [yggdrasil-network/yggdrasil-android#2]

**Comment by neilalexander** [comment]
This should be an option in your device’s VPN settings already for any VPN extension.

**Comment by styromaniac** [comment]
Where?

**Comment by neilalexander** [comment]
On the Pixel 4a with Android 11 that I have here, it's at:

"Settings" app -> "Network & internet" -> "Advanced" -> "VPN" -> press the ⚙️ next to "Yggdrasil" -> check "Always-on VPN" option.

**Comment by styromaniac** [comment]
Oh. I'll try that.

**Comment by styromaniac** [comment]
![Screenshot_20210813-230211_Nova Launcher.jpg](https://user-images.githubusercontent.com/43807387/129432356-9a1cee5a-417f-49cb-9f16-91e360422989.jpg)

![Screenshot_20210813-230319_Yggdrasil.jpg](https://user-images.githubusercontent.com/43807387/129432371-34834922-c4f9-489b-98bd-66843ee83e9e.jpg)

I get this when I reboot. Yggdrasil doesn't enable at boot.

**Comment by bqv** [comment]
Ditto. Has to be manually turned on even when "always-on".

**Comment by neilalexander** [comment]
I've improved Always-On VPN support in the [latest build](https://github.com/yggdrasil-network/yggdrasil-android/releases/tag/v0.1-007) but it's possible the UI will still misbehave in some cases.

**Comment by styromaniac** [comment]
The app appears to crash on connection change now.
