### ISSUE TITLE
Remove DNS Server dialog has no button

### ISSUE THREAD

**Issue by sparrowme** [yggdrasil-network/yggdrasil-android#44]
Release 0.1 (013)

Dialog works if you tap in bottom right corner.  But if you "miss" the server is not removed.

![image](https://user-images.githubusercontent.com/1423504/224330643-8df5e32b-b71d-4ff7-9b4f-351558606d08.png)

Also noting that when I retested this for the screen shot, it let me add a DNS server without entering any IP - hence no IP in screenshot.

**Comment by batyshkaLenin** [comment]
@Revertron Please close this issue, it is fixed in #50
