### ISSUE TITLE
Cannot connect to domain names

### ISSUE THREAD

**Issue by Chaz6** [yggdrasil-network/yggdrasil-android#5]
When yggdrasil is connected I can connect to hosts using plain ip addresses, but for some reason android refuses to connect when given a domain that points to the same ip address.

**Comment by Chaz6** [comment]
Probably invalid.

**Comment by styromaniac** [comment]
I'm having the same issue.![Screenshot_20210727-124942_Chrome.jpg](https://user-images.githubusercontent.com/43807387/127195119-83baf3bc-6686-490e-a508-933bf4b226dd.jpg)

**Comment by styromaniac** [comment]
I would re-open this issue if I were you.
