### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [yggdrasil-network/yggdrasil-android#58]
...as the submodule used by F-Droid was deemed "unused": https://github.com/yggdrasil-network/yggdrasil-android/commit/ca45b37baa303c9a5a969e6861f7c4d742d45368

maybe we can set it up as a [srclib](https://f-droid.org/docs/Build_Metadata_Reference/#build_srclibs) instead, but we don't have a version reference: https://github.com/yggdrasil-network/yggdrasil-android/blob/v0.1-017/.github/workflows/android.yml#L26 since the submodule was providing that

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/aad111d43d8fae946c23fad838f305cb524df965

**Comment by neilalexander** [comment]
This is likely my fault as I didn't know that there were F-Droid builds depending upon that submodule. It can be added back if so.

**Comment by licaon-kter** [comment]
Like I said, we used the submodulex for that, as that's usable for you too, eg. Use it in your CI, and then it's a given that you don't forget to update

We can extract the exact version of it from a file, but devs tend to forget to update those too :))

**Comment by neilalexander** [comment]
Happy to use the submodule for CI too. Right now it just pulls in the latest: https://github.com/yggdrasil-network/yggdrasil-android/blob/6a66960666c718516b89cefffd4d504d3e9ec3f1/.github/workflows/android.yml#L21-L27

... but I'm happy to take the recommendation to use the submodule for both for consistency.

**Comment by Revertron** [comment]
So, what are we doing? I'm ready to release something.

**Comment by linsui** [comment]
It has been added back. I also updated the metadata to use it.
