### ISSUE TITLE
Split tunneling

### ISSUE THREAD

**Issue by exu-g** [yggdrasil-network/yggdrasil-android#72]
I'd like a configuration option for the VPN, so it is only used for traffic to the Yggdrasil network. Other traffic should not use the VPN and instead go through the default routing table.  

The current situation is causing issues when I'm on a non-ipv6 enabled network and try to access to an ipv6 enabled service. In that case, a first connection attempt will be made through an Yggdrasil node, fail because I have ip forwarding disabled on the node and retry using the non-yggdrasil ipv4. This makes browsing much slower in general as many sites support ipv6 and have to wait for a timeout first before retrying ipv4.

Based on what I found, this is not really possible with the default VPN API in Android, but maybe can be implemented as an advanced feature with root/shizuku permissions.

**Comment by neilalexander** [comment]
The VPN is already "split tunnel", the only route to the TUN adapter is 200::/7 and even if more traffic did get captured by the interface, Yggdrasil will simply drop any traffic outside of that range.

Unfortunately Android is mistaking the Yggdrasil address for having IPv6 internet connectivity. I don't think there's anything we can do about it.

**Comment by exu-g** [comment]
Thank you for the explanation.  
In that case I'll have to look into some form of routing through another VPN.  

I'm closing this issue, maybe Android will fix this in the future and it could be explored again :)  
Thanks for your work
