### ISSUE TITLE
Unable to Scroll Peers List

### ISSUE THREAD

**Issue by styromaniac** [yggdrasil-network/yggdrasil-android#8]
![Screenshot_20210726-172937_Yggdrasil.jpg](https://user-images.githubusercontent.com/43807387/127061776-3e44efd8-62f1-4c96-85a5-982889430961.jpg)

When I have a bunch of peers, they go off screen and I can't scroll down.

**Comment by neilalexander** [comment]
I suspect this is a simple case of not having an enclosing scroll view, so should be an easy fix.
