### ISSUE TITLE
DNS servers

### ISSUE THREAD

**Issue by ACLzz** [yggdrasil-network/yggdrasil-android#9]
Hello, I like your app and I want to use it, but also it would be greate if you add feature to choose custom dns server, like in crisp repo. It is killing feature for me

**Comment by styromaniac** [comment]
I need to be able to use NextDNS. I have a Handshake subdomain pointing to my Yggdrasil site address:

http://y.styromaniac.creator/

**Comment by Revertron** [comment]
I'm in a test mode with this feature already. I think tomorrow will file a PR for that :)
